# Generated by Django 5.2.4 on 2025-07-27 11:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_alter_user_is_active_alter_user_is_admin_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="city",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
